package langdet

import (
	"testing"

	"golang.org/x/text/language"
)

func TestDetectParagraphs(t *testing.T) {
	for _, testcase := range []struct {
		Tag       language.Tag
		Paragraph string
	}{
		// European languages.
		{language.Albanian, `Interneti është sistemi i rrjeteve kompjuterike të ndërlidhur që përdor Suitën e Protokollit të Internetit (TCP/IP) për të lidhur miliarda pajisje në të gjithë botën. Ai është një rrjet i rrjeteve që përbëhet nga miliona rrjete private, publike, akademike, biznese, dhe qeveritare, me fushëveprim lokal deri në global, të lidhura nga një koleksion i gjerë elektronik, wireless, dhe teknologjitë e rrjeteve optike. Interneti mbart një gamë të gjerë të burimeve të informacionit dhe shërbimeve, të tilla si dokumentet e ndërlidhura hypertext dhe aplikacionet e World Wide Web (WWW), posta elektronike, telephony, dhe rrjetet peer-to-peer për file sharing.`},
		{BelarusianTag, `Інтэрнэ́т[1][2][3] (англ.: Internet, ад Interconnected Networks — аб’яднаныя сеткі) — глабальная тэлекамунікацыйная сетка інфармацыйных і вылічальных рэсурсаў, якую ў 1989 годзе распрацавалі брытанскі навуковец Цім Бернерс-Лі і бельгійскі — Роберт Каё.`},
		{BosnianTag, `Internet jest sistem međusobno povezanih računarskih mreža koji pomoću paketa internetskih protokola (TCP/IP) ostvaruju komunikaciju između raznih vrsta uređaja i mreža. Ta skupina mreža sastoji se od privatnih, javnih, akademskih, poslovnih i vladinih mreža lokalnog do globalnog opsega, povezanih raznim vrstama elektronskih, bežičnih i optičkih tehnologija umrežavanja. Internet sadrži veliki raspon informativnih resursa i usluga, poput međusobno povezanih dokumenata hiperteksta i aplikacija "svjetske mreže" (WWW), elektronske pošte, telefonije i razmjene datoteka.`},
		{language.Bulgarian, `Интернет или глобалната мрежа, а в разговорния български език и накратко като нет (от английското net, мрежа), е глобална система от свързани компютри в мрежа или дори компютърни мрежи, която работи чрез стандартизиран комплект от протоколи TCP/IP, които позволяват свързването между компютрите и съответните интернет устройства`},
		// {language.Croatian, `Internet ili međumrežje javno je dostupna globalna podatkovna mreža koja povezuje računala i računalne mreže služeći se internetskim protokolom (IP) za njihovu komunikaciju. To je mreža svih mrežā koja se sastoji od milijuna kućnih, akademskih, poslovnih i vladinih mreža koje međusobno razmjenjuju informacije i usluge kao što su elektronička pošta, chat i prijenos datoteka te povezane stranice i dokumente World Wide Weba.`},
		{language.Croatian, `Internet je 1969. godine osnovalo Američko Ministarstvo obrane. Zvao se ARPANET (prva četiri slova su kratica za Advanced Research Project Agency – Agencija za napredne istraživačke projekte, dok net označava računalnu mrežu[1]). Cilj te mreže je bio da se poveže određeni broj računala u SAD-u.[1] Radilo se o skupoj ideji, no Ministarstvu obrane SAD-a novac nije nedostajao.[1] Arpanet je imao faktor koji je kasnije bio ključan za nastanak i popularizaciju interneta;[1] tijekom šezdesetih godina vladao je hladni rat, zbog čega je Ministarstvo obrane SAD-a strahovalo da bi se mogao dogoditi nuklearni napad. Inženjeri su morali projektirati Arpanet tako da on radi čak i ako se baci bomba na dio uspostavljene mreže te se uništi, dakle, čak i ako dio komunikacijskog dijela bude uništen, ostatak mreže treba nastaviti funkcionirati bez problema.[1] `},
		{language.Czech, `Internet je celosvětový systém propojených počítačových sítí („síť sítí“), ve kterých mezi sebou počítače komunikují pomocí rodiny protokolů TCP/IP. Společným cílem všech lidí využívajících internet je bezproblémová komunikace (výměna dat).`},
		{language.Danish, `Et internet er betegnelsen for et netværk af computernetværk, som er koblet sammen.[kilde mangler] Ofte taler man om internettet, der så betegner et globalt netværk af datanet-værter (computere). Internettet er en af de vigtigste opfindelser fra det 20. århundrede.[ifølge hvem?][kilde mangler] Ikke fordi det i sig selv er noget teknisk vidunder,[ifølge hvem?] men på grund af de store konsekvenser det allerede har for vores måde at leve vores liv på, selv om det kun har nået større udbredelse inden for de seneste 16 år.[siden hvornår?][kilde mangler]`},
		{language.Dutch, `Het internet is een wereldwijd openbaar netwerk van computernetwerken, waarvan de afspraken worden beschreven in de Request for Comments die worden beheerd door de Internet Engineering Task Force. Om het internet goed te laten werken, zijn afspraken gemaakt over protocollen voor gegevensuitwisseling tussen computers. Een van die protocollen is het Internetprotocol (IP).`},
		{language.English, `The Internet (or internet)[a] is the global system of interconnected computer networks that uses the Internet protocol suite (TCP/IP)[b] to communicate between networks and devices. It is a network of networks that consists of private, public, academic, business, and government networks of local to global scope, linked by a broad array of electronic, wireless, and optical networking technologies. The Internet carries a vast range of information resources and services, such as the inter-linked hypertext documents and applications of the World Wide Web (WWW), electronic mail, telephony, and file sharing.`},
		{language.Estonian, `Kõige lihtsamalt öeldes on Internet suur hulk omavahel ühendatud arvuteid. Selleks, et arvutid omavahel suhelda saaksid, kasutatakse paljusid protokolle. Protokoll on sisuliselt lihtsalt üks reegel või reeglite kogum, mis määrab, kuidas midagi tehakse. Ilma protokollideta ei oleks võimalik omavahel infot vahetada. Tänapäeval arvatakse olevat internetti ühendatud seadmeid 20 miljardi kandis[2].`},
		{language.Finnish, `Internet (puhekielessä usein "verkko", "netti") on maailmanlaajuinen toisiinsa kytkettyjen tietoverkkojen järjestelmä, joka käyttää internet-protokollaa (TCP/IP) yhdistämään tietoteknisiä laitetta toisiinsa. Se on tietoverkkojen tietoverkko, joka koostuu eri kokoisista miljoonista yksityisistä, julkisista, akateemisista, liike-elämän sekä valtiohallintojen tietoverkoista, jotka kytkeytyvät toisiinsa erilaisten teknisten laitteistojen avulla (esim. langattomat ja optiset verkkoteknologiat). Internetissä on laaja valikoima erilaisia tietovarantoja ja -palveluita, kuten esimerkiksi web-sivut, sähköposti, puhelinpalvelut, nettipelit ja tiedostojen jakamiseen käytetyt vertaisverkot. Rajoitetummassa teknisessä merkityksessä "internet" tarkoittaa mitä tahansa TCP/IP-protokollaperhettä käyttävää verkkoa, vaikka se ei olisi yhteydessä maailmanlaajuiseen Internetiin.`},
		{language.French, `Internet est un réseau informatique mondial accessible au public. Il s'agit d'un réseau de réseaux, à commutation de paquets, sans centre névralgique, composé de millions de réseaux aussi bien publics que privés, universitaires, commerciaux et gouvernementaux, eux-mêmes regroupés en réseaux autonomes ; il en existe plus de 91 000 en 20191. L'information est transmise via Internet grâce à un ensemble standardisé de protocoles de transfert de données, qui permet des applications variées comme le courrier électronique, le World Wide Web, la messagerie instantanée, le partage de fichiers en pair-à-pair, le streaming, le podcasting, la téléconférence.`},
		{language.German, `Das Internet (von englisch interconnected networks ‚zusammengeschaltete Netzwerke‘, kürzer englisch internetwork oder kurz net ‚Netz‘), umgangssprachlich auch Netz, ist ein weltweiter Verbund von Rechnernetzwerken, den autonomen Systemen. Es ermöglicht die Nutzung von Internetdiensten wie WWW, E-Mail, Telnet, SSH, XMPP, MQTT und FTP. Dabei kann sich jeder Rechner mit jedem anderen Rechner verbinden. Der Datenaustausch zwischen den über das Internet verbundenen Rechnern erfolgt über die technisch normierten Internetprotokolle. Die Technik des Internets wird durch die RFCs der Internet Engineering Task Force (IETF) beschrieben.`},
		{language.Hungarian, `Az internet olyan globális számítógépes hálózat, amelyen a számítógépek az internetprotokoll (IP) segítségével kommunikálnak. Felhasználók milliárdjait kapcsolja össze és lehetővé teszi olyan elosztott rendszerek működtetését, mint például a világháló (World Wide Web, WWW).`},
		{language.Icelandic, `Internetið er alþjóðlegt kerfi tölvuneta sem nota IP-samskiptastaðalinn til að tengja saman tölvur um allan heim og myndar þannig undirstöðu undir ýmsar netþjónustur, eins og veraldarvefinn, tölvupóst og fleira. Í daglegu tali er oft talað um netið þegar átt er við Internetið.`},
		{IrishTag, `Is líonra ríomhairí poiblí é an tIdirlíon, nó an tIdirghréasán, a nascann líonraí ríomhaireachta ar fud an domhain ag úsáid córais theileachumarsáide phoiblí. Seoltar sonraí mar mheascán de chomharthaí analógacha agus comharthaí digiteacha thar an Idirlíon. Caithfear seoladh uathúil a bheith ag gach ríomhaire atá ceangailte go díreach leis an Idirlíon. Tugtar an seoladh IP air seo.`},
		{language.Italian, `Internet[1] è una rete di telecomunicazioni ad accesso pubblico che connette vari dispositivi o terminali in tutto il mondo, rappresentando dalla sua nascita uno dei maggiori mezzi di comunicazione di massa (assieme a radio e televisione),[2][3][4] grazie all'offerta all'utente di una vasta serie di contenuti potenzialmente informativi e di servizi.`},
		{LatinTag, `Gallia est omnis divisa in partes tres, quarum unam incolunt Belgae, aliam Aquitani, tertiam qui ipsorum lingua Celtae, nostra Galli appellantur. 2 Hi omnes lingua, institutis, legibus inter se differunt. Gallos ab Aquitanis Garumna flumen, a Belgis Matrona et Sequana dividit`},
		{language.Latvian, `Internets ir publiski pieejama savstarpēji saslēgtu datortīklu vispasaules sistēma, kas pārsūta datus, izmantojot Interneta protokolu (IP). Tas ir veidots no tūkstošiem mazāku komerciālu, akadēmisku un valdību tīklu. Tas ietver elektronisko pastu, tērzēšanas retranslēšanu, datņu pārraidi, tīmekļa dokumentus, sociālos tīklus utt.`},
		{language.Lithuanian, `Interneto protokolai turi kelis lygius. Žemiausiame lygyje (kuris reikalingas visiems aukštesniems) naudojami IPv4 ar IPv6 protokolai, kiekvienam kompiuteriui suteikiant tuo metu unikalų IP adresą. Kitame lygyje, ryšiui tarp kompiuterių palaikyti naudojami TCP/IP ir UDP protokolai. Jie sukuria kanalą duomenims perduoti. Dar aukštesniame lygyje naudojami konkrečiam tikslui skirti protokolai (HTTP – tinklalapiams perduoti, SMTP – elektroniniam paštui, FTP – paskiroms byloms siųsti ir pan).`},
		{LuxembourgishTag, `D'Internet (Ofkierzung fir Interconnected Networks) ass e weltwäiten Zesummeschloss vu Computernetzwierker déi op de verschiddensten Technologië berouen, an deen d'Benotze vun Internetdéngschter wéi WWW, E-Mail, Telnet, Usenet an FTP erméiglecht a sou der Kommunikatioun an dem Austausch vun Informatioun déngt. Dat Netz vun Netzer kënnt dem Benotzer awer wéinst enger komplexer Internet-Software, déi all Detailer verstoppt, als eenheetlecht homogeent Netz vir. Dofir gëtt och dacks vun engem virtuellen Netz geschwat.`},
		{language.Macedonian, `Интернет (англиски: Internet) или семрежје — јавно достапен систем на меѓусебно поврзани сметачки мрежи од целиот свет, кои пренесуваат податоци во форма на пакети со користење на стандардното множество протоколи означено како TCP/IP. Се состои од голем број мали и големи, домашни, деловни владини и невладини мрежи, коишто заедно пренесуваат различни информации и услуги, како електронска пошта, директен разговор, како и меѓусебно поврзани мрежни места (websites) и други документи од Мрежата (Светска мрежа — World Wide Web, WWW).`},
		{MalteseTag, `Il-Wikipedija huwa proġett enċiklopediku kollaborattiv, universali, multilingwi u jaħdem abbażi tal-prinċipju wiki. L-għan ewlieni tal-Wikipedija huwa li tipprovdi kontenut ħieles, newtrali u verifikabbli, li kulħadd jista' jimmodifika u jtejjeb.`},
		{NorwegianBokmålTag, `Internett (ofte kalt «nettet», ble stavet med stor I ifølge Språkrådet inntil 2015, da det ble valgfri med liten eller stor I[1]) er et verdensomspennende datanettverk og danner grunnlag for en rekke kommunikasjonstjenester. De viktigste er World Wide Web, e-post, chat, filoverføring, IP-telefoni og videomøter. Internett ble tatt i bruk i akademiske miljøer tidlig i 1980-årene, men etter at World Wide Web ble alment tilgjengelig omkring 1995 fikk nettet en eksplosiv økning i trafikk og utbredelse. Siden 1995 har internett blitt et viktig medium for informasjonsspredning, mellommenneskelig kommunikasjon, handel og forvaltning, og stadig flere anvendelser kommer til.`},
		{NorwegianNynorskTag, `Internett er eit verdsomfattande ope datanett basert på protokollane TCP/IP. I Noreg er (2005) 64 prosent av alle privathushaldningar tilknytte til Internett, og den vanlegaste måten å kopla seg opp på, er via ADSL. 41 prosent (2005) av alle nordmenn som er på nett, har tilgang via breiband heimefrå. To av dei mest kjende tenestene på Internett er e-post og Verdsveven. Datamaskina over heile verda er kopla saman i eit nettverk, og det er dette store nettet som vi kallar Internett.`},
		{language.Polish, `Internet (skrótowiec od ang. inter-network, dosłownie „między-sieć”) – ogólnoświatowy system połączeń między komputerami, określany również jako sieć sieci[1][2]. W definicji informatycznej Internet to przestrzeń adresów IP przydzielonych hostom i serwerom połączonym za pomocą urządzeń sieciowych, takich jak karty sieciowe, modemy i koncentratory, komunikujących się za pomocą protokołu internetowego z wykorzystaniem infrastruktury telekomunikacyjnej.`},
		{language.Portuguese, `A Internet[1] é um sistema global de redes de computadores interligadas que utilizam um conjunto próprio de protocolos (Internet Protocol Suite ou TCP/IP) com o propósito de servir progressivamente usuários no mundo inteiro. É uma rede de várias outras redes, que[2] consiste de milhões de empresas privadas, públicas, acadêmicas e de governo, com alcance local e global e que está ligada por uma ampla variedade de tecnologias de rede eletrônica, sem fio e ópticas.`},
		{language.Romanian, `Substantivul propriu „Internet” (scris cu majusculă) desemnează o rețea mondială unitară de calculatoare și alte aparate cu adrese computerizate, interconectate conform protocoalelor (regulilor) de comunicare „Transmission Control Protocol” și „Internet Protocol”, numite împreună „stiva TCP/IP”. Precursorul Internetului datează din 1965, când Agenția pentru Proiecte de Cercetare Înaintate de Apărare - a Ministerului Apărării, Department of Defense sau DoD din SUA (Defence Advanced Research Projects Agency, DARPA) a creat prima rețea de computere interconectate sub numele ARPAnet.`},
		{language.Russian, `Интерне́т[1] (англ. Internet, МФА: [ˈɪn.tə.net]) — информационно-коммуникационная сеть и всемирная система объединённых компьютерных сетей для хранения и передачи информации[2]. Раньше упоминался как Всемирная сеть и Глобальная сеть, а также просто Сеть. Построена на базе стека протоколов TCP/IP[3]. На основе Интернета работает Всемирная паутина (World Wide Web, WWW) и множество других систем передачи данных`},
		{language.Serbian, `Интернет је светски систем повезаних рачунарских мрежа који је трансформисао начин на који функционишу комуникациони системи. Почеци интернета се вежу за стварање ARPANET-а 1969. године, мреже рачунара под контролом Министарства одбране САД. Данас интернет повезује милијарде рачунара широм света на један нехијерархијски начин`},
		{language.Spanish, `Internet (el internet o, también, la internet)3​ es un conjunto descentralizado de redes de comunicaciones interconectadas, que utilizan la familia de protocolos TCP/IP, lo cual garantiza que las redes físicas heterogéneas que la componen constituyen una red lógica única de alcance mundial. Sus orígenes se remontan a 1969, cuando se estableció la primera conexión de computadoras, conocida como ARPANET, entre tres universidades en California (Estados Unidos).`},
		{language.Slovak, `Internet (z angl. interconnected networks – prepojené siete; hovorovo: net, sieť) je verejne dostupný celosvetový systém vzájomne prepojených počítačových sietí, ktoré prenášajú dáta pomocou prepínania paketových dát s použitím štandardizovaného Internetového Protokolu (IP) a mnohých ďalších protokolov. Pozostáva z tisícok menších komerčných, nekomerčných, akademických, súkromných, vládnych a vojenských počítačových sietí`},
		{language.Slovenian, `Internet ali medomrežje (mednarodni izraz internet je skrajšan iz angleške besede »inter-network«) je v splošnem smislu računalniško omrežje, ki povezuje več omrežij. Kot lastno ime je Internet javno razpoložljiv mednarodno povezan sistem računalnikov skupaj z informacijami in uslugami za uporabnike. Sistem uporablja način paketno preklopljivih komunikacijskih protokolov TCP/IP. Tako se največje medomrežje enostavno imenuje Internet. Spretnost povezovanja omrežij na ta način se imenuje internetno delovanje.`},
		{language.Swedish, `Internet, av engelskans mellannätverk, är världens största datornätverk. World Wide Web, e-post, fildelning, ip-tv och ip-telefoni är populära tjänster på internet. Internet sammanblandas ofta med World Wide Web, som är en internettjänst för att enkelt manövrera sig mellan så kallade webbsidor och andra filer som finns lagrade på särskilda servrar (så kallade webbplatser).`},
		{language.Turkish, `İnternet, çok protokollü bir ağ olup birbirine bağlı bilgisayar ağlarının tümü olarak da tanımlanabilir. Binlerce akademik ve ticari ağ ile devlet ve serbest bilgisayar ağının birbirine bağlanmasıyla oluşmuştur`},
		{language.Ukrainian, `Інтерне́т (від англ. Internet), міжнародна комп'ютерна мережа, всемере́жжя[1][2], (дослівно) міжмере́жа[3], міжмере́жжя[4][5][6][7] — всесвітня система сполучених комп'ютерних мереж, що заснована на комплекті Інтернет-протоколів. Інтернет також називають мережею мереж, бо він складається з мільйонів локальних і глобальних приватних, публічних, академічних, ділових і урядових мереж, пов'язаних між собою з використанням різноманітних дротових`},
	} {
		t.Run(testcase.Tag.String(), func(t *testing.T) {
			lang := DetectLanguage([]byte(testcase.Paragraph))
			if lang != testcase.Tag {
				t.Error("got", lang, "but expected", testcase.Tag)
			}
		})
	}
}
